name: Auth Service Build and Deploy

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: myauthserviceimage

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Build Jar
        working-directory: Auth-Application
        run: mvn clean package -DskipTests

      - name: Upload Jar
        uses: actions/upload-artifact@v4
        with:
          name: spring-jar
          path: Auth-Application/target/*.jar

  docker-build:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download Jar
        uses: actions/download-artifact@v4
        with:
          name: spring-jar
          path: Auth-Application/target

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        working-directory: Auth-Application
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }} .

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}

  deploy:
    needs: docker-build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}

            docker stop myauthserviceapp || true
            docker rm myauthserviceapp || true

            docker run -d \
              --name myauthserviceapp \
              -p 8080:8087 \
              -e DB_URL=jdbc:mysql://mysqlcontainer:3306/employee \
              -e DB_USERNAME=root \
              -e DB_PASSWORD=1808 \
              --network my_auth_service_network \
              ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}

            docker image prune -f